### ISSUE TITLE
Find SVD file by MCU model name

### ISSUE THREAD

**Issue by KivApple** [posborne/cmsis-svd#37]
I think in some cases developer don't know which SVD file is needed for specified MCU. He can store some matching table (mcu -> vendor, filename), but there is exists better solution. Something like this:

```
def find_for_mcu(mcu):
    mcu = mcu.lower()
    vendors = resource_listdir("cmsis_svd", "data")
    for vendor in vendors:
        fnames = resource_listdir("cmsis_svd", "data/%s" % vendor)
        for fname in fnames:
            filename = fname.lower()
            if not filename.endswith(".svd"):
                continue
            filename = filename[:-4]
            if mcu.startswith(filename):
                return vendor, fname
        for fname in fnames:
            filename = fname.lower()
            if not filename.endswith(".svd"):
                continue
            filename = "^%s.*" % filename[:-4].replace('x', '.')
            if re.match(filename, mcu):
                return vendor, fname
    return None, None
```

Some vendors use "X" character in SVD file name as "any character" pattern.
My code can find suitable SVD file by MCU model name (e. g. STM32F103C8T6), but I access to internal structures of package cmsis-svd and this is not good (you can change file layout in future).
I suggest add some function like this to your package. For example, add constructor SVDParser.from_mcu_name in addition to SVD.for_packaged_svd.
I can create pull request if you will accept this change. Or maybe you know better algorithm to translate MCU name to pair vendor:filename.

**Comment by posborne** [comment]
I think I would accept a patch adding this functionality as a helper of sorts (similar to `for_package_svd`).  The svd python code may not always ship with the actual definitions, but in that case it is expected that a function like this will not work.

If you go ahead with a PR, please be sure to add a few unit tests so that if the directory structure changes in the future, the maintainers are reminded to update the implementation.
